import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

config = {
    "videoDuration": 912,
    "fps": 30,
    "videoSrc": "video_preview.mp4",
    "titles": [
        {"id": "t01", "startSec": 0.5, "endSec": 8.0, "text": "Comorbidades associadas\nao autismo", "style": "hero"},
        {"id": "t02", "startSec": 3.0, "endSec": 12.0, "text": "Dra. Elizangila Leite|Palestrante - Mestra em TEA - Escritora", "style": "credit"},
        {"id": "t03", "startSec": 11.5, "endSec": 20.0, "text": "O autismo nunca vem sozinho", "style": "kinetic"},
        {"id": "t04", "startSec": 36.5, "endSec": 46.0, "text": "Comorbidades nao excluem\no diagnostico de autismo", "style": "quote"},
        {"id": "t05", "startSec": 52.5, "endSec": 62.0, "text": "90% dos autistas|tem alguma comorbidade", "style": "counter"},
        {"id": "t06", "startSec": 55.0, "endSec": 62.0, "text": "Ate 40% tem mais de uma", "style": "lower3rd"},
        {"id": "t07", "startSec": 62.0, "endSec": 72.0, "text": "TDAH", "style": "flash"},
        {"id": "t08", "startSec": 76.5, "endSec": 90.0, "text": "70 a 80%", "style": "counter"},
        {"id": "t09", "startSec": 90.0, "endSec": 100.0, "text": "Nem todo TDAH e autista...|...mas a maioria dos autistas tem TDAH", "style": "quote"},
        {"id": "t10", "startSec": 125.5, "endSec": 140.0, "text": "Desatento|Hiperativo|Misto", "style": "panel"},
        {"id": "t11", "startSec": 140.0, "endSec": 154.0, "text": "TRES SUBTIPOS DE TDAH", "style": "ribbon"},
        {"id": "t12", "startSec": 154.5, "endSec": 165.0, "text": "TRANSTORNO DE ANSIEDADE", "style": "kinetic"},
        {"id": "t13", "startSec": 157.0, "endSec": 167.0, "text": "64 a 80%", "style": "counter"},
        {"id": "t14", "startSec": 172.5, "endSec": 185.0, "text": "Mais observada no\npublico feminino", "style": "lower3rd"},
        {"id": "t15", "startSec": 187.5, "endSec": 200.0, "text": "DEPRESSAO", "style": "flash"},
        {"id": "t16", "startSec": 195.0, "endSec": 205.0, "text": "54%", "style": "counter"},
        {"id": "t17", "startSec": 214.5, "endSec": 226.0, "text": "Nivel 1 de suporte", "style": "lower3rd"},
        {"id": "t18", "startSec": 235.5, "endSec": 248.0, "text": "Sente-se estranha...|...percebe que e diferente", "style": "quote"},
        {"id": "t19", "startSec": 259.0, "endSec": 278.0, "text": "67% ja tiveram\nideacao suicida", "style": "counter"},
        {"id": "t20", "startSec": 278.0, "endSec": 292.0, "text": "30 A 35% TENTARAM SUICIDIO", "style": "ribbon"},
        {"id": "t21", "startSec": 300.5, "endSec": 315.0, "text": "Nivel 1 tem inteligencia preservada...|...sabe como planejar", "style": "quote"},
        {"id": "t22", "startSec": 336.5, "endSec": 352.0, "text": "NIVEIS DE SUPORTE\nNAO QUANTIFICAM DOR", "style": "kinetic"},
        {"id": "t23", "startSec": 362.5, "endSec": 378.0, "text": "Nivel 1: pesado para si|Nivel 2-3: pesado para familia|Todos sofrem", "style": "panel"},
        {"id": "t24", "startSec": 411.5, "endSec": 425.0, "text": "DISTURBIOS DE SONO", "style": "kinetic"},
        {"id": "t25", "startSec": 420.0, "endSec": 435.0, "text": "80%", "style": "counter"},
        {"id": "t26", "startSec": 435.0, "endSec": 455.0, "text": "Insonia|Sono fragmentado|Dificuldade de iniciar|Dificuldade de manter", "style": "panel"},
        {"id": "t27", "startSec": 468.5, "endSec": 490.0, "text": "Cerebro que nao descansa...|...nao consegue ser feliz", "style": "quote"},
        {"id": "t28", "startSec": 527.5, "endSec": 548.0, "text": "Sem sono - irritacao|Irritacao - hipersensibilidade|Hipersensibilidade - crise", "style": "panel"},
        {"id": "t29", "startSec": 579.5, "endSec": 592.0, "text": "CICLO VICIOSO DO SONO", "style": "ribbon"},
        {"id": "t30", "startSec": 593.5, "endSec": 608.0, "text": "SINDROME DO INTESTINO IRRITAVEL", "style": "kinetic"},
        {"id": "t31", "startSec": 625.5, "endSec": 640.0, "text": "Sensibilidade a\nproblemas gastricos", "style": "lower3rd"},
        {"id": "t32", "startSec": 642.5, "endSec": 658.0, "text": "Lactose|Caseina|Gluten", "style": "panel"},
        {"id": "t33", "startSec": 674.5, "endSec": 688.0, "text": "INFLAMACAO INTESTINAL", "style": "flash"},
        {"id": "t34", "startSec": 695.5, "endSec": 710.0, "text": "Intestino inflamado nao absorve\nnutrientes corretamente", "style": "lower3rd"},
        {"id": "t35", "startSec": 733.5, "endSec": 748.0, "text": "Constipacao ou diarreia", "style": "lower3rd"},
        {"id": "t36", "startSec": 769.5, "endSec": 785.0, "text": "DISBIOSE", "style": "flash"},
        {"id": "t37", "startSec": 784.5, "endSec": 800.0, "text": "Microbiota intestinal", "style": "lower3rd"},
        {"id": "t38", "startSec": 824.5, "endSec": 838.0, "text": "Alergia|Disbiose|Inflamacao", "style": "panel"},
        {"id": "t39", "startSec": 838.5, "endSec": 855.0, "text": "TRANSTORNO BIPOLAR", "style": "kinetic"},
        {"id": "t40", "startSec": 869.5, "endSec": 883.0, "text": "Bipolaridade pode coexistir\ncom o espectro autista", "style": "quote"},
        {"id": "t41", "startSec": 883.5, "endSec": 898.0, "text": "PROCESSAMENTO SENSORIAL", "style": "kinetic"},
        {"id": "t42", "startSec": 890.0, "endSec": 905.0, "text": "80 a 90%", "style": "counter"},
    ],
    "brolls": [
        {"id": "b01", "startSec": 0.5, "endSec": 11.0, "src": "broll_01.mp4", "label": "Brain neurons"},
        {"id": "b02", "startSec": 36.5, "endSec": 48.0, "src": "broll_06.mp4", "label": "Doctor consultation"},
        {"id": "b03", "startSec": 62.0, "endSec": 74.0, "src": "broll_08.mp4", "label": "Kids ADHD"},
        {"id": "b04", "startSec": 125.5, "endSec": 137.5, "src": "broll_12.mp4", "label": "Brain MRI"},
        {"id": "b05", "startSec": 154.5, "endSec": 166.5, "src": "broll_09.mp4", "label": "Anxiety"},
        {"id": "b06", "startSec": 187.5, "endSec": 199.5, "src": "broll_05.mp4", "label": "Depression"},
        {"id": "b07", "startSec": 235.5, "endSec": 247.5, "src": "broll_10.mp4", "label": "Person alone"},
        {"id": "b08", "startSec": 259.0, "endSec": 271.0, "src": "broll_13.mp4", "label": "Woman crying"},
        {"id": "b09", "startSec": 336.5, "endSec": 348.5, "src": "broll_02.mp4", "label": "Woman thinking"},
        {"id": "b10", "startSec": 411.5, "endSec": 423.5, "src": "broll_03.mp4", "label": "Insomnia"},
        {"id": "b11", "startSec": 435.0, "endSec": 447.0, "src": "broll_04.mp4", "label": "Clock ticking"},
        {"id": "b12", "startSec": 527.5, "endSec": 539.5, "src": "broll_01.mp4", "label": "Brain neurons"},
        {"id": "b13", "startSec": 593.5, "endSec": 605.5, "src": "broll_07.mp4", "label": "Stomach pain"},
        {"id": "b14", "startSec": 642.5, "endSec": 654.5, "src": "broll_11.mp4", "label": "Healthy food"},
        {"id": "b15", "startSec": 769.5, "endSec": 781.5, "src": "broll_14.mp4", "label": "DNA microbiota"},
        {"id": "b16", "startSec": 838.5, "endSec": 850.5, "src": "broll_15.mp4", "label": "Emotional bipolar"},
        {"id": "b17", "startSec": 883.5, "endSec": 895.5, "src": "broll_16.mp4", "label": "Sensory overload"},
    ],
    "zooms": [
        {"id": "z01", "startSec": 29.0, "endSec": 52.0, "direction": "in", "intensity": 1.12},
        {"id": "z02", "startSec": 99.0, "endSec": 125.0, "direction": "out", "intensity": 1.15},
        {"id": "z03", "startSec": 202.0, "endSec": 235.0, "direction": "in", "intensity": 1.12},
        {"id": "z04", "startSec": 455.0, "endSec": 468.0, "direction": "out", "intensity": 1.15},
        {"id": "z05", "startSec": 710.0, "endSec": 733.0, "direction": "in", "intensity": 1.12},
        {"id": "z06", "startSec": 800.0, "endSec": 824.0, "direction": "out", "intensity": 1.15},
        {"id": "z07", "startSec": 11.0, "endSec": 18.5, "direction": "hardIn", "intensity": 1.35, "originY": 30},
        {"id": "z08", "startSec": 62.0, "endSec": 76.0, "direction": "hardIn", "intensity": 1.3, "originY": 32},
        {"id": "z09", "startSec": 140.0, "endSec": 154.0, "direction": "hardIn", "intensity": 1.35, "originY": 28},
        {"id": "z10", "startSec": 165.0, "endSec": 172.0, "direction": "hardIn", "intensity": 1.3, "originY": 35},
        {"id": "z11", "startSec": 187.0, "endSec": 202.0, "direction": "hardIn", "intensity": 1.35, "originY": 30},
        {"id": "z12", "startSec": 248.0, "endSec": 259.0, "direction": "hardIn", "intensity": 1.3, "originY": 32},
        {"id": "z13", "startSec": 292.0, "endSec": 300.0, "direction": "hardIn", "intensity": 1.35, "originY": 28},
        {"id": "z14", "startSec": 352.0, "endSec": 362.0, "direction": "hardIn", "intensity": 1.3, "originY": 35},
        {"id": "z15", "startSec": 411.0, "endSec": 420.0, "direction": "hardIn", "intensity": 1.3, "originY": 30},
        {"id": "z16", "startSec": 490.0, "endSec": 511.0, "direction": "hardIn", "intensity": 1.25, "originY": 33},
        {"id": "z17", "startSec": 548.0, "endSec": 569.0, "direction": "hardIn", "intensity": 1.3, "originY": 30},
        {"id": "z18", "startSec": 608.0, "endSec": 625.0, "direction": "hardIn", "intensity": 1.35, "originY": 32},
        {"id": "z19", "startSec": 658.0, "endSec": 674.0, "direction": "hardIn", "intensity": 1.3, "originY": 28},
        {"id": "z20", "startSec": 748.0, "endSec": 769.0, "direction": "hardIn", "intensity": 1.35, "originY": 35},
        {"id": "z21", "startSec": 838.0, "endSec": 854.0, "direction": "hardIn", "intensity": 1.3, "originY": 30},
        {"id": "z22", "startSec": 883.0, "endSec": 896.0, "direction": "hardIn", "intensity": 1.35, "originY": 32},
    ],
    "sfx": []
}

with (ROOT / "public" / "edit_config.json").open("w", encoding="utf-8") as f:
    json.dump(config, f, ensure_ascii=False, indent=2)

print(f"Config saved: {len(config['titles'])} titles, {len(config['brolls'])} brolls, {len(config['zooms'])} zooms")
